### ISSUE TITLE
README Suggestions

### ISSUE THREAD

**Issue by josh4trunks** [abishai/Zoneminder-port#14]
Hi @abishai
I had some suggestions for the README. If you prefer I can post a bug/patch on bugs.freebsd.org

1) I'm not sure exactly what file users are beng told to edit?

```
PHP throws warning if date.timezone option is not set. The best place 
    to do it is an ini file in /usr/local/etc/php"
```

What I always do is "cp /usr/local/etc/php.ini-production /usr/local/etc/php.ini"
And change settings in /usr/local/etc/php.ini. Is this what you meant?

2) This statement can be removed; database.php now reads the config automatically

```
    Additionally, you must also edit 
    /usr/local/www/zoneminder/api/app/Config/database.php in a similar 
    manner. Scroll down and change login and password to the values you created in the previous step.
```

**Comment by abishai** [comment]
No, no, no bugs on bugs.freebsd.org. That system scare me, lol
1. Actually, I prefer not to touch php.ini, because it's hard to track changes between php releases. There is directory /usr/local/etc/php, where user can create override ini files. php extenstions, for example attached here. So, I just create the new file and write thatever I need.
2. OK

**Comment by josh4trunks** [comment]
sounds good! Ok, so I understand that you create a php.ini in /usr/local/etc/php, then what you wrote for (1) is fine =]

**Comment by josh4trunks** [comment]
Another thing I noticed, it seems PHP dependencies weren't being pulled in for me.
I think we need to change `PHP=` to `USE_PHP`.

Also, why do we have `IGNORE_WITH_PHP= 70`? I'm going to try php70 and see if it works.

**Comment by abishai** [comment]
Yes, I've noticed we habe issues with PHP. Can you check USE_PHP knob? Also, we need to add php56-sockets. It's used by api for zms communications.

I remember I saw bug report with issues under php7

**Comment by josh4trunks** [comment]
USE_PHP seems like the proper way to do it, https://github.com/freebsd/freebsd-ports/blob/master/Mk/bsd.php.mk#L16

Yeah, I noticed `socket` was causing me errors too!

**Comment by josh4trunks** [comment]
I got my production system setup and working with php70. It looks like php70 issues have already been resolved https://github.com/ZoneMinder/ZoneMinder/issues/1405

So here are the changes we need...
- Remove **database.php** mention in README
- `PHP= json pdo_mysql session` > `USE_PHP= json pdo_mysql session sockets`
- Remove `IGNORE_WITH_PHP= 70`

**Comment by josh4trunks** [comment]
Ohh and on the forum it was mentioned **gd** would helpful for ZMNinja.

I suggest we add it like the optional dependencies in owncloud. probably on by default?

```
OPTIONS_DEFINE= NLS V4L GD DOCS
OPTIONS_DEFAULT= NLS GD
GD_DESC= ZMNinja Support
GD_USE= PHP=gd
```

**Comment by abishai** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210442

**Comment by josh4trunks** [comment]
Nice, that was quick! Gonna close this issue then.

One other thing to remember for v1.30 is this line can be removed.
`${REINPLACE_CMD} -e 's|sizeof(loc_addr.sun_family))+1|sizeof(loc_addr.sun_family)+1)|g' ${WRKSRC}/src/zm_stream.cpp`

**Comment by josh4trunks** [comment]
@abishai 
Not critical, just something to add next time we update this port.

In the README.FreeBSD file, section '**1.3 Install www/fcgiwrap**', we forgot to add `service fcgiwrap start`

**Comment by abishai** [comment]
OK :)
What do you think about to push h264 version of ZM to ports?

**Comment by josh4trunks** [comment]
ohh that's ready? if its not stable couldn't someone just edit the version number / gitcommit to build it themselves?

**Comment by josh4trunks** [comment]
are you running it? thats gonna be really nice once it is ready =]

**Comment by abishai** [comment]
This GH contains updated version of ZM with h264 backend. I checked it's compiling, but I'm not running it. However, I tried it before and found that h.264 encoding from mjpeg is worthless - CPU pressure is too high (ZM is not supporing hardware acceleration) and we have very tricky bug - encoded files are empty (but contain proper mp4 headers, just with empty track).

The h.264 passthrough was OK and I think this is how ZM should be used if you have h264 capable cameras. It works without significant CPU hit. 
Camera (h264) -> direct file write. Analytics is done as usual with ffmpreg backend and it just binding to existing h264 file like - event is linked to file and contains frame numbers. HTTP interface was rather buggy and actually WIP, but ZM Ninja seems to be OK.

**Comment by josh4trunks** [comment]
ahh, I look forward to that working well!

My home setup uses low resolution mjpeg streams for analysis, so h264 passthrough of the main stream would be great for me. Though I would need this to work in the webbrowser since that is how I check in on my dog from work, lol. I wonder if this will support h265 as well, one of my cameras has that and I use that stream cause it gives a superior picture.

**Comment by abishai** [comment]
I thought it's not possible to use different stream for analysis with ZM. Or you use low quality stream as trigger for the main one?

**Comment by josh4trunks** [comment]
yeah they trigger the HD stream. the monitors are linked

**Comment by abishai** [comment]
Interesting. With h264 backend I'd want mocord - even zfs dies on zillions of jpegs, so maybe I should try this trick.
