### ISSUE TITLE
zmNinja support in FreeBSD

### ISSUE THREAD

**Issue by rajil** [abishai/Zoneminder-port#15]
It will be helpful if you can include the dependencies to make zmNinja also functional in FreeBSD. The top level packages in my jail are:
```
ftp/curl
www/fcgiwrap
databases/mysql56-server
www/nginx
textproc/php56-ctype
ports-mgmt/pkg
editors/vim-lite
multimedia/zoneminder
```

**Comment by abishai** [comment]
ZMNinja is functional. Only ctype dependency is missing

**Comment by rajil** [comment]
Thanks. Any thoughts on https://github.com/pliablepixels/zmNinja/issues/373
