### ISSUE TITLE
Issues I'm aware of

### ISSUE THREAD

**Issue by abishai** [abishai/Zoneminder-port#4]
Issues I'd like to fix before port submit
~~1. FreeBSD sendfile support: reproducable Sig4  https://gist.github.com/abishai/85541fb7e61ac61b0a8c
Crash is here https://github.com/ZoneMinder/ZoneMinder/blob/fe46785e94081d86b6dfb565c423198b52855c77/src/zm_sendfile.h#L18
Now, SENDFILE is disabled in port~~
~~2. Only for x64. https://gist.github.com/abishai/45af2e17ba5115c5d3c15de59066f60b time_t is int in i386. I suppose, we should go long instead of time_t~~
3. 'soc'  files problem. https://gist.github.com/abishai/2c11cda4db6f045ae1a4b0a9a7cbc6e4
Problem is here https://github.com/ZoneMinder/ZoneMinder/blob/247cb3d0b2adb8941bd1cd400cf783bdfc71832d/src/zm_stream.cpp#L326
We need to add +1 to buffer length. But why ? Use preprocessor directive for BSD platform or find the root of the problem?

**Comment by josh4trunks** [comment]
I have a couple other things I'd suggest we get done before this replaces the 1.25 version in the ports tree. I'll work on trying to get these done soon.

##### HOPEFULLY BY RELEASE
- [x] Add the needed PHP dependencies
  - I believe these need to be installed on the same server as the compile binaries?
- [x] have the config installed using the @sample function
  - https://www.freebsd.org/doc/en/books/porters-handbook/plist-config.html
- [x] allow prefixed arguments to be passed to the init script like "onestart"
- [x] remove mysql service from the requirements of the init script. Otherwise users utilizing a networked / centralized mysql server can't start zoneminder.
- [ ] zoneminder  project release a stable release so we can pull in an official tag number

##### FUTURE WISHLIST
- [ ] Add more optional stuff like libvlc support. ~~Also option related, is V4L for local camera devices? I would guess most people would want to use primarily IP cameras and this should be disabled by default. But, I could be wrong~~
- [x] Document what should be done for port setup (like zm_create.sql) in `pkg-message`. ~~Also anything that may be important. I haven't tried yet myself, but does something special with `sysvipc` need to be enabled?~~
  - https://www.freebsd.org/doc/en/books/porters-handbook/pkg-files.html#porting-message

**Comment by josh4trunks** [comment]
~~Also, I noticed the addition of `-DCMAKE_REQUIRED_INCLUDES:STRING="${LOCALBASE}/include"` was breaking my port compilation. I'm testing on a FreeBSD x64 10.3 jail with V4L off.~~
**EDIT** This is working for me now

```
A failure has been detected in another branch of the parallel make

make[5]: stopped in /tmp/Zoneminder-port/work/ZoneMinder-5a3978f/onvif/proxy
--- onvif/proxy/CMakeFiles/zmonvifproxy ---
*** [onvif/proxy/CMakeFiles/zmonvifproxy] Error code 2

make[4]: stopped in /tmp/Zoneminder-port/work/ZoneMinder-5a3978f
1 error

make[4]: stopped in /tmp/Zoneminder-port/work/ZoneMinder-5a3978f
--- onvif/proxy/CMakeFiles/zmonvifproxy.dir/all ---
*** [onvif/proxy/CMakeFiles/zmonvifproxy.dir/all] Error code 2

make[3]: stopped in /tmp/Zoneminder-port/work/ZoneMinder-5a3978f
2 errors

make[3]: stopped in /tmp/Zoneminder-port/work/ZoneMinder-5a3978f
*** [all] Error code 2

make[2]: stopped in /tmp/Zoneminder-port/work/ZoneMinder-5a3978f
1 error

make[2]: stopped in /tmp/Zoneminder-port/work/ZoneMinder-5a3978f
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make[1]: stopped in /tmp/Zoneminder-port
*** Error code 1

Stop.
make: stopped in /tmp/Zoneminder-port
```

**Comment by abishai** [comment]
According suggestions:
1. Formally, not. However I can't imagine user case for that. Dependencies are very trivial, however I don't have exact list yet. pdo-mysql is for backend.
2. I remember I did it.
7. Maybe to add readme file. ZM has some for different linux distros.

About error: 
I didn't notice compilation error on my side. Your log doesn't consist the actual error place, scroll log somewhere upper or use MAKE_JOBS_UNSAFE.

**Comment by josh4trunks** [comment]
I just commented it out and will deal with the error later. Trying to tackle the easy stuff for me first, lol

PHP dependencies are listed here
https://wiki.archlinux.org/index.php/ZoneMinder#PHP
https://github.com/freebsd/freebsd-ports/blob/master/multimedia/zoneminder/Makefile#L35

But, what I'll do is run nginx+php-fpm and see what extensions it complains about and document them.

**Comment by abishai** [comment]
BTW, was it yours patches that allowed ZM 1.28 compilation under FreeBSD ? If yes, sendfile code is yours. :) I tried to debug it, however I'm not a C programmer, so I found only the place of error. Signal4 is so strange for me. Is it stack corruption?

**Comment by josh4trunks** [comment]
Nope, not mine. I never touched C code, lol. only mess with freebsd ports, nginx configs, and occasionally PHP.

If you're on ZFS you wouldn't want sendfile anyway, so in many case we'd want to disable it =]

**Comment by abishai** [comment]
Ok, let's keep it disabled.

**Comment by abishai** [comment]
https://github.com/ZoneMinder/ZoneMinder/pull/1450
We should wait this one to be merged. It addresses tha last blocker issue from my list.

**Comment by abishai** [comment]
I rewrite readme slightly. Grammar tweaks and suggestions will be endorsed  :-)

**Comment by josh4trunks** [comment]
looks great! when I have a chance I can make some small grammar tweaks.

I also noticed your missing copy the php.ini and setting a timezone. this was required in my testing.
also, you didn't uncomment the PATH part I had in php-fpm, this is needed for php-fpm to see executables installed from ports, like "zip"

**Comment by abishai** [comment]
Right. I forgot about timezone, this is mandatory.
Interesting, so it has problems with zip? I suppose chrooted php is out of luck here. I'll look on zip call first.

**Comment by abishai** [comment]
https://github.com/ZoneMinder/ZoneMinder/blob/fe46785e94081d86b6dfb565c423198b52855c77/web/skins/classic/includes/export_functions.php#L940
Meh. That code stinks :(

**Comment by abishai** [comment]
Looks like export_functions.php is directly from php3 era. Necromancers on the loose :-1:

**Comment by josh4trunks** [comment]
yeah, I guess it relies in the zip executable being available.

I think owncloud does this with php-zip extension, which could be a future project for someone.

**Comment by josh4trunks** [comment]
Apparently the 'soc' problem was fixed here
https://github.com/ZoneMinder/ZoneMinder/commit/413eced6df833a1867c26172b9448bd9210b52e5

But, now I can't get the zoneminder service to start with commit number `9377dca`. Here's the error I'm hitting.

```
May 11 00:25:33 zm zmdc[10936]: ERR [Unable to unlink /var/run/zm/zmdc.sock]
May 11 00:25:35 zm zmdc[10936]: ERR ['zmc -m 9' exited abnormally, exit status 255]
May 11 00:25:35 zm zma_m9[10966]: ERR [Shared data not initialised by capture daemon for monitor Garage-SD]
May 11 00:25:35 zm zmdc[10936]: ERR ['zmc -m 10' exited abnormally, exit status 255]
May 11 00:25:35 zm zmdc[10936]: ERR ['zma -m 9' exited abnormally, exit status 255]
May 11 00:25:35 zm zmdc[10936]: FAT [Can't execute log entry 'insert into Logs ( TimeKey, Component, Pid, Level, Code, Message, File, Line ) values ( ?, ?, ?, ?, ?, ?, ?, NULL )': ]
May 11 00:25:35 zm zmpkg[10925]: ERR [Unable to run "sudo -u www /usr/local/bin/zmdc.pl start zmfilter.pl", output is "Unable to connect to server"]
May 11 00:25:35 zm zma_m10[10974]: ERR [Shared data not initialised by capture daemon for monitor Garage]
```

~~When you have a chance to try this, please confirm if you get the same error and we can file a bug report. But don't rush, enjoy your time off! I just wanted to document this before I work on other things. Thanks~~ This was fixed =]

**Comment by josh4trunks** [comment]
You're 3rd point here was fixed I believe.
https://github.com/abishai/Zoneminder-port/issues/4#issue-150673121

I think this port is ready to diffed and submitted to bugs.freebsd.org as soon as 1.30.0 is released. I suggest we do the following...
- update the Makefile so it pulls from the github release tag (no longer need to specify the commit)
- move `@dir(%%WWWOWN%%,%%WWWGRP%%,) %%WWWDIR%%/api/app/tmp` to above, the other `@dir` lines. Since this is the way `make makeplist` lists them
- add your email as the maintainer =P

**Comment by abishai** [comment]
If 1.30.0 will work under FreeBSD. As I see in their github, master is broken atm.
Can we use bugs@freebsd email as maintainer? I'am expecting a lot of questions and bug reports.

**Comment by josh4trunks** [comment]
that note is old, they reverted a change and its working.

**Comment by josh4trunks** [comment]
sure, I dont want to be the mainter either lol.

**Comment by abishai** [comment]
devel/p5-Data-Dump
devel/p5-SOAP-WSDL
devel/p5-UUID
net/p5-IO-Socket-Multicast

this should be added to handle onvif deps

**Comment by josh4trunks** [comment]
@abishai 
I noticed a few things you might want to change in **pkg-plist**
- %%SITE_PERL%%/ZoneMinder/ConfigData.pm.in.bak should be removed (this should manually done when using `make makeplist`)
- I suggest you reorder the last part so it matches what `make makeplist` would generate. Would make analyzing diffs from the automatic generation easier. This could also be reordered in **Makefile** but you might want a specific order there for other reasons

From ...

```
@dir(%%WWWOWN%%,%%WWWGRP%%,) %%WWWDIR%%/events
@dir(%%WWWOWN%%,%%WWWGRP%%,) %%WWWDIR%%/images
@dir(%%WWWOWN%%,%%WWWGRP%%,) %%WWWDIR%%/temp
@dir(%%WWWOWN%%,%%WWWGRP%%,) %%WWWDIR%%/api/app/tmp
@dir(%%WWWOWN%%,%%WWWGRP%%,) /var/run/zm
@dir(%%WWWOWN%%,%%WWWGRP%%,) /var/tmp/zm
```

To...

```
@dir(%%WWWOWN%%,%%WWWGRP%%,) %%WWWDIR%%/api/app/tmp
@dir(%%WWWOWN%%,%%WWWGRP%%,) %%WWWDIR%%/events
@dir(%%WWWOWN%%,%%WWWGRP%%,) %%WWWDIR%%/images
@dir(%%WWWOWN%%,%%WWWGRP%%,) %%WWWDIR%%/temp
@dir(%%WWWOWN%%,%%WWWGRP%%,) /var/run/zm
@dir(%%WWWOWN%%,%%WWWGRP%%,) /var/tmp/zm
```

**Comment by abishai** [comment]
Done.
I think the port is ready for release.
Can you test if it builds under FreeNAS ? I remember they still use 9.x codebase.

**Comment by josh4trunks** [comment]
sure, I'll test it and report back

**Comment by josh4trunks** [comment]
It's working well =]

There is a small bug...
`${CP} ${WRKSRC_crud}/* ${WRKSRC}/web/api/app/Plugin/Crud` 
fails because there are directories in there, the below fixes it
`${CP} -R ${WRKSRC_crud}/* ${WRKSRC}/web/api/app/Plugin/Crud`

**Comment by abishai** [comment]
Thanks!
So, let's release it ? :)

**Comment by josh4trunks** [comment]
yeah sound good!

might as well post it on bugs.freebsd.org. then while it's being reviewed we can edit the version info/checksum once 1.30 is out

**Comment by abishai** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210007

**Comment by josh4trunks** [comment]
I think the proper way is to give a diff of the current port directory.
I'd have the new port namesd zoneminder, old port named zoneminder-orig then run a 'diff -ruN'

**Comment by abishai** [comment]
It would be the diff indeed - everything differs! :)

**Comment by josh4trunks** [comment]
congrats, looks like its commited! we just gotta resubmit the diff for v1.30 official

**Comment by abishai** [comment]
Log:
  multimedia/zoneminder: 1.25.0 -> 1.30.0
- submitter becomes maintainer

:(

**Comment by josh4trunks** [comment]
lol, sorry about that. I can file the bug for the version updates. you just gotta review and approve.

hopefully you dont need to support this in other ways.
