### ISSUE TITLE
Suggestions for DOCS

### ISSUE THREAD

**Issue by josh4trunks** [abishai/Zoneminder-port#8]
Hey @abishai 
I see you're working hard on this port and added the DOCS stuff!
Here's some suggestions, I can make a PR tonight if needed.
- use `PORTDOCS` instead of `DOCS`, and don't include these in `pkg-plist`
  - I'm not sure why you changed this to DOCS? maybe to work around error messages because of adding these to pkg-plist?
- install docs in a `post-install-DOCS-on` target, otherwise I feel install would error with `DOCS` disabled
  - example - https://github.com/freebsd/freebsd-ports/blob/master/news/sabnzbdplus/Makefile#L72-76
- remove "COPYING" and "LICENSE" from `PORDOCS`, I think this will be automatically be added because the `LICENSE` is set

Source
https://www.freebsd.org/doc/en/books/porters-handbook/install.html

**Comment by abishai** [comment]
Yeah, I have some time today. I made a dummy file for readme; if you with you can write actual readme, using one from distros folder.

Actually, I used random port as example. pkg-plist %%PORTDOCS%% supports conditional DOCS option.  Well, I can try PORTDOCS method.

**Comment by josh4trunks** [comment]
Looks like you got this done, so I'll close this. Only suggestion would be to change INSTALL_DATA to INSTALL_MAN

I'll work on the freebsd readme as well and submit something today/tomorrow.
