### ISSUE TITLE
Cant export anything

### ISSUE THREAD

**Issue by josh4trunks** [abishai/Zoneminder-port#9]
It looks like zoneminder needs ${WWWDIR}/temp to exist and be writable, or it can't export anything.
`Can't open event export list file 'temp/zmFileList.txt'`

This can be fixed same as creating the events/images folder in Makefile and pkg-plist.
What I don't get is why zoneminder needs so many temp directories?!

**Comment by josh4trunks** [comment]
This is another bug, but also related. I noticed browsing to ZONEMINDER_IP/api was giving me issues.
${WWWDIR}/api/app/tmp should also be created and writable

**Comment by josh4trunks** [comment]
ohh, and to get zip export working you need `zip` installed. Not sure if you think we should make this a dependency/ optional dependency.

**Comment by josh4trunks** [comment]
Everything mentioned here is fixed by https://github.com/abishai/Zoneminder-port/pull/10

**Comment by abishai** [comment]
> What I don't get is why zoneminder needs so many temp directories?!

The same reason it needs sudo for start :-D
